#
# Need to turn to programs to lib. Non-recursive make, unit tests...
#
.PHONY : all clean check

TARGETS := rotate sign squash myrotate myrotate-2
CC := gcc
CFLAGS := -Wall -Werror
CXXFLAGS := $(CFLAGS)

all: $(TARGETS)

clean:
	$(RM) $(TARGETS)
