#
# Need to turn to programs to lib. Non-recursive make, unit tests...
#
.PHONY : all clean check

TARGETS := i18n seven-seg
CC := gcc
CFLAGS := -Wall -Werror
CXXFLAGS := $(CFLAGS)

all: $(TARGETS)

clean:
	$(RM) $(TARGETS)
